### ISSUE TITLE
INTERNALPLUGINSPATH returns wrong path "Resources/plugsin/XPPython3"

### ISSUE THREAD

**Issue by marangonico** [pbuckner/x-plane_plugins#16]
INTERNALPLUGINSPATH returns a wrong path "Resources/plugsin/XPPython3"
It should be "Resources/plugins/XPPython3"

**Comment by pbuckner** [comment]
true, but that's only in the stub file (stubs/XPPython.py). 

You must not use stub files in executable code -- it's merely to assist a linter / code editor.

plugins.c (and therefore XPPython3.xpl returns correct value.

**Comment by pbuckner** [comment]
stubs/XPPython.py updated

**Comment by marangonico** [comment]
> true, but that's only in the stub file (stubs/XPPython.py).
> You must not use stub files in executable code -- it's merely to assist a linter / code editor.

I'm not distributing stub files, but in my environment I'm using a symlink inside the PythonPlugins folder pointing to the source folder where stubs are located too.

**Comment by pbuckner** [comment]
I’ve updated stubs.zip. Not sure using symlink will work as that would get pulled in during execution (even if only for your local testing). 

Recommended approach is to have stubs somewhere “else”, and pull them in only via lint configuration such as

.pylintrc
[MASTER]
init-hook=“import sys; sys.path.extend([‘/Volumes/code/XPPython/stubs’, ‘/Volumes/X-Plane/Resources/plugins/XPPython’])"

In any case, I’ve updated stubs (thanks for letting me know) and whatever works for your development environment is what counts!
--
  Peter Buckner
