### ISSUE TITLE
Please add menu item to "reset logs"

### ISSUE THREAD

**Issue by devleaks** [pbuckner/x-plane_plugins#18]
With development, XPPython3.log can grow quite large.
I'd love to truncate it from time to time.
Would it be possible to add a menu item to do so?
I naively tried to create a plugin to reset the file, but after truncating the file xpython fills it with 0 and numbers only.
Thank you.

**Comment by pbuckner** [comment]
Log is cleared before every restart. You're asking to truncate the log _during_  execution?

**Comment by devleaks** [comment]
Yes. But I don’t know if it is a good idea. You need the info at the start of the file (versions, script loaded, etc.). When debugging, you sometimes want to only see your lines. tail -f does it to some extend. But I noticed weird things when you truncate the file in an editor (buffer in play?). So adding a menu item to gracefully stop writing to the file and restart a new one might be a nice debugging addition.

**Comment by pbuckner** [comment]
Yes we keep the logfile open, so (you) attempting to truncate it won't work. For debugging, wouldn't using your own (plugin-specific) log be better?

**Comment by devleaks** [comment]
Yes, you’re right. I’ll use my own log in a next release. I’ll only keep important plugin start/enable messages in xppython3.log.

**Comment by pbuckner** [comment]
That's what Joan does with NOAA weather plugin (his weather server runs as a separate process & therefore _needs_ to have it's own log.

Anyway, keep me posted if problems -- I just updated the plugin to 3.0.9: some people are reporting installation problems (though I have no more details) ... have you upgraded yet?

**Comment by devleaks** [comment]
Not yet. I’m away from my xplane computer. I’m reading the addition to the xppython3 manual and imgui stuff. I’ll upgrade Tuesday. I have a double python set up on a M1 Mac mini, python intel for x-plane, python arm for machine learning (both 3.9).

**Comment by pbuckner** [comment]
Just to be careful, as I don't know why some people are having problems with the upgrade, you might COPY your current XPPython3 folder and stash it somewhere prior to upgrade. That way if upgrade fails, you can delete the attempted upgrade and copy back known working version.
