### ISSUE TITLE
XPLMSendMessageToPlugin: inParam type should not be checked against 'integer'

### ISSUE THREAD

**Issue by marangonico** [pbuckner/x-plane_plugins#2]
I'm trying to notify a custom dref to ""xplanesdk.examples.DataRefEditor" plugin.
The inparam should be the signature of the custom dataref.

The call is:
`XPLMSendMessageToPlugin(plugin_id, MSG_ADD_DATAREF, signature)`

These are the 3 params passed to XPLMSendMessageToPlugin():
```
* plugin_id=2
* MSG_ADD_DATAREF=16777216
* signature="nm/four_seasons/season"
```

The error raised is TypeError: an integer is required (got type str), which leads to inparam.

```
Traceback (most recent call last):
  File "./Resources/plugins/PythonPlugins\PI_four_seasons.py", line 568, in flightmodel_loop_callback
    self.custom_drefs.notify_datarefeditor(plugin_id)
  File "./Resources/plugins/PythonPlugins\four_seasons\XPDref.py", line 132, in notify_datarefeditor
    XPLMSendMessageToPlugin(plugin_id, MSG_ADD_DATAREF, signature)
TypeError: an integer is required (got type str)


```

**Comment by pbuckner** [comment]
Fixed in a6, we support integer and strings now (I tested by registering a dataref with datarefeditor, so this should work fine for you.
